test(mqtt connector): fix flaky test
Apparently, the reason might alternate between `closed` and `{tcp_closed, _}`.

```
Error: -12T13:33:40.119395+00:00 [error] msg: failed_to_start_connection_process, cause: maxlimit, listener: 0.0.0.0:1883
Warning: 2T13:33:40.119704+00:00 [warning] msg: ingress_client_connect_failed, name: <<"connector:mqtt:t_connect_with_more_clients_than_the_broker_accepts-576460752303419311">>, reason: {tcp_closed,#Port<0.1035>}, explain: <<"Your MQTT connection attempt was unsuccessful. It might be at its maximum capacity for handling new connections. To diagnose the issue further, you can check the server logs for any specific messages related to the unavailability or connection limits.">>
Warning: 2T13:33:40.119764+00:00 [warning] msg: ingress_client_connect_failed, name: <<"connector:mqtt:t_connect_with_more_clients_than_the_broker_accepts-576460752303419311">>, reason: {tcp_closed,#Port<0.1037>}, explain: <<"Your MQTT connection attempt was unsuccessful. It might be at its maximum capacity for handling new connections. To diagnose the issue further, you can check the server logs for any specific messages related to the unavailability or connection limits.">>
Warning: 2T13:33:40.120037+00:00 [warning] msg: ingress_client_connect_failed, name: <<"connector:mqtt:t_connect_with_more_clients_than_the_broker_accepts-576460752303419311">>, reason: closed
```

https://github.com/emqx/emqx/actions/runs/15611644433/job/43974468897?pr=15372#step:5:521